"""
Title: The Fallen Castle 
Creators:Hayden and Jishaan
Description: Knite kills drangon while tring to get coins
"""
# Tilemap
scene.set_tile_map(img("""
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    5d5d5ddddddddddd
    dddddddddddddddd
    888888ddd5dd8888
    dddddddddddddddd
    ddddddd88888dddd
    dddddddddddddddd
    d8888ddddddddddd
    ddddddd888ddd5dd
    dd5d5ddddddddddd
    ddddddddddd8888d
    d8888888dddddddd
    dddddddddddddddd
    ddddddddd888888d
    dddddddddddddddd
    ddddd8888dddd5dd
    d5d5d5dddddddddd
    dddddddddd888888
    88888888dddddddd
    dddddddddddddddd
    dddddd8888dddddd
    dddddddd5ddddddd
    d888ddddddd888dd
    dddddd8888dddddd
    dddddddddddddddd
    dddddddddddddddd
    d88888ddddd88888
    ddddddd5d5dddddd
    dddddddddddddddd
    dd5ddd8888dddddd
    dddddddddddddddd
    d8888dddddd8888d
    dddddddddddddddd
    dddddddddddddddd
    dddddddddddddddd
    dddddd88888ddddd
    dddddddddddddddd
    dddddddddddddddd
    2222222222222222
    2222222222222222
    2222222222222222
"""))
# Knight
knight = sprites.create(img("""
    .......2..................................................................................
    ......222.................................................................................
    .....11111................................................................................
    ....1111111...............................................................................
    ....1eeeee1...............................................................................
    ....eeeeeee...............................................................................
    ....e1eee1e...............................................................................
    ....e8eee8e...............................................................................
    ....eefeeee...............................................................................
    ....feeffef...............................................................................
    .....feeef................................................................................
    ...ff.fff.ff......e.......................................................................
    ..f111727111fffffee.......................................................................
    .f111172711111111ee.......................................................................
    .f111172711111111ee.......................................................................
    .f11117271111ffffee.......................................................................
    .f11117271111f............................................................................
    .f1111727111f.............................................................................
    .f111172711f..............................................................................
    ..eee17271f...............................................................................
    ..eee17271f...............................................................................
    ..eeff555ff...............................................................................
    ..ee111f111...............................................................................
    ....111f111...............................................................................
    ....111f111...............................................................................
    ....111f111...............................................................................
    ....111f111...............................................................................
    ....111f111...............................................................................
    ...66f6.6f66..............................................................................
    .6f6f66.66f6f6............................................................................
    .66f666.666f66............................................................................
    ..........................................................................................
"""))
# knight.set_position(0,120)
controller.move_sprite(knight)
scene.camera_follow_sprite(knight)